### ISSUE TITLE
NoMethodError (undefined method `arity') after upgrade to Ruby 3 and Rails 6.1

### ISSUE THREAD

**Issue by abartov** [zendesk/property_sets#85]
I've been using property_sets without issue for a couple of years.  I'm working on upgrading a Rails 5.2 app to Ruby 3.0 and Rails 6.1.  Rails starts, but every request fails with this error:
```
NoMethodError (undefined method `arity' for {:class_name=>"UserPreference", :autosave=>true, :dependent=>:destroy, :inverse_of=>:user}:Hash):
```
My declaration (in class User) is:
```
    property_set :preferences do
      property :fontsize, default: '2'
      property :activated, default: 'false' 
    end
```
Relevant stack trace:
```
activerecord (6.1.3.1) lib/active_record/associations/builder/association.rb:53:in `build_scope'
activerecord (6.1.3.1) lib/active_record/associations/builder/association.rb:47:in `create_reflection'
activerecord (6.1.3.1) lib/active_record/associations/builder/association.rb:32:in `build'
activerecord (6.1.3.1) lib/active_record/associations.rb:1458:in `has_many'
property_sets (3.7.0) lib/property_sets/active_record_extension.rb:47:in `property_set'
app/models/user.rb:19:in `<class:User>'
```

It seems to me it may be a bug in property_sets, perhaps related to this recent commit? c9710f505b6b87398ff7f281daf42570a118afb0

**Comment by abartov** [comment]
No, that commit isn't it; it happens with gem version 3.6.0 as well, this time with this stack trace:
```
activerecord (6.1.3.1) lib/active_record/associations/builder/association.rb:53:in `build_scope'
activerecord (6.1.3.1) lib/active_record/associations/builder/association.rb:47:in `create_reflection'
activerecord (6.1.3.1) lib/active_record/associations/builder/association.rb:32:in `build'
activerecord (6.1.3.1) lib/active_record/associations.rb:1458:in `has_many'
property_sets (3.6.0) lib/property_sets/active_record_extension.rb:28:in `block in property_set'
activesupport (6.1.3.1) lib/active_support/core_ext/kernel/reporting.rb:15:in `block in silence_warnings'
activesupport (6.1.3.1) lib/active_support/core_ext/kernel/reporting.rb:28:in `with_warnings'
activesupport (6.1.3.1) lib/active_support/core_ext/kernel/reporting.rb:15:in `silence_warnings'
property_sets (3.6.0) lib/property_sets/active_record_extension.rb:27:in `property_set'
app/models/user.rb:19:in `<class:User>'
```

**Comment by abartov** [comment]
It would seem the immediate error has to do with Ruby 3.0's keyword arguments and its removed tolerance for implicit conversion of hashes.  The code does work in Ruby 2.7.x.

**Comment by abartov** [comment]
Thank you.  Could you push out the 3.7.1 version of the gem? It does not seem to have been pushed to RubyGems.

**Comment by bquorning** [comment]
@abartov Sorry for the day here. I have just pushed v3.7.1 to rubygems now.
